### PR TITLE
Fix unit tests & setup.py file

### PR DESCRIPTION
**Pull request by JafarAbdi**
Fix: https://github.com/ros-planning/srdfdom/issues/92
Fix: https://github.com/ros-planning/srdfdom/issues/93

### CODE REVIEW

**Comment by JafarAbdi** [comment]
@ooeygui Could you please test/review this PR .?

**Comment by ooeygui** [comment]
Thank you for the quick turnaround - testing now

**Comment by ooeygui** [comment]
Confirmed working on ubuntu.

**Comment by ooeygui** [comment]
Looks like the Windows release hasn't caught up with the pytest issues, so I had to manually revert `pip install pytest==6.0.2` - https://github.com/ms-iot/ROSOnWindows/issues/330.

Looks like we're missing some exports for Windows when building. Taking a look.
```
test_parser.obj : error LNK2019: unresolved external symbol "private: static class std::vector<struct srdf::Model::JointProperty,class std::allocator<struct srdf::Model::JointProperty> > const srdf::Model::empty_vector_" (?empty_vector_@Model@srdf@@0V?$vector@UJointProperty@Model@srdf@@V?$allocator@UJointProperty@Model@srdf@@@std@@@std@@B) referenced in function "public: class std::vector<struct srdf::Model::JointProperty,class std::allocator<struct srdf::Model::JointProperty> > const & __cdecl srdf::Model::getJointProperties(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)const " (?getJointProperties@Model@srdf@@QEBAAEBV?$vector@UJointProperty@Model@srdf@@V?$allocator@UJointProperty@Model@srdf@@@std@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@4@@Z) [C:\ws\moveit2_ws\build\srdfdom\test_cpp_C.vcxproj]
C:\ws\moveit2_ws\build\srdfdom\Release\test_cpp_C.exe : fatal error LNK1120: 1 unresolved externals [C:\ws\moveit2_ws\build\srdfdom\test_cpp_C.vcxproj]
test_parser.obj : error LNK2019: unresolved external symbol "private: static class std::vector<struct srdf::Model::JointProperty,class std::allocator<struct srdf::Model::JointProperty> > const srdf::Model::empty_vector_" (?empty_vector_@Model@srdf@@0V?$vector@UJointProperty@Model@srdf@@V?$allocator@UJointProperty@Model@srdf@@@std@@@std@@B) referenced in function "public: class std::vector<struct srdf::Model::JointProperty,class std::allocator<struct srdf::Model::JointProperty> > const & __cdecl srdf::Model::getJointProperties(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)const " (?getJointProperties@Model@srdf@@QEBAAEBV?$vector@UJointProperty@Model@srdf@@V?$allocator@UJointProperty@Model@srdf@@@std@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@4@@Z) [C:\ws\moveit2_ws\build\srdfdom\test_cpp_nl_NL.UTF-8.vcxproj]
C:\ws\moveit2_ws\build\srdfdom\Release\test_cpp_nl_NL.UTF-8.exe : fatal error LNK1120: 1 unresolved externals [C:\ws\moveit2_ws\build\srdfdom\test_cpp_nl_NL.UTF-8.vcxproj]
```

**Comment by JafarAbdi** [comment]
> Looks like the Windows release hasn't caught up with the pytest issues, so I had to manually revert `pip install pytest==6.0.2` - [ms-iot/ROSOnWindows#330](https://github.com/ms-iot/ROSOnWindows/issues/330).
> 
> Looks like we're missing some exports for Windows when building. Taking a look.
> 
> ```
> test_parser.obj : error LNK2019: unresolved external symbol "private: static class std::vector<struct srdf::Model::JointProperty,class std::allocator<struct srdf::Model::JointProperty> > const srdf::Model::empty_vector_" (?empty_vector_@Model@srdf@@0V?$vector@UJointProperty@Model@srdf@@V?$allocator@UJointProperty@Model@srdf@@@std@@@std@@B) referenced in function "public: class std::vector<struct srdf::Model::JointProperty,class std::allocator<struct srdf::Model::JointProperty> > const & __cdecl srdf::Model::getJointProperties(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)const " (?getJointProperties@Model@srdf@@QEBAAEBV?$vector@UJointProperty@Model@srdf@@V?$allocator@UJointProperty@Model@srdf@@@std@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@4@@Z) [C:\ws\moveit2_ws\build\srdfdom\test_cpp_C.vcxproj]
> C:\ws\moveit2_ws\build\srdfdom\Release\test_cpp_C.exe : fatal error LNK1120: 1 unresolved externals [C:\ws\moveit2_ws\build\srdfdom\test_cpp_C.vcxproj]
> test_parser.obj : error LNK2019: unresolved external symbol "private: static class std::vector<struct srdf::Model::JointProperty,class std::allocator<struct srdf::Model::JointProperty> > const srdf::Model::empty_vector_" (?empty_vector_@Model@srdf@@0V?$vector@UJointProperty@Model@srdf@@V?$allocator@UJointProperty@Model@srdf@@@std@@@std@@B) referenced in function "public: class std::vector<struct srdf::Model::JointProperty,class std::allocator<struct srdf::Model::JointProperty> > const & __cdecl srdf::Model::getJointProperties(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)const " (?getJointProperties@Model@srdf@@QEBAAEBV?$vector@UJointProperty@Model@srdf@@V?$allocator@UJointProperty@Model@srdf@@@std@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@4@@Z) [C:\ws\moveit2_ws\build\srdfdom\test_cpp_nl_NL.UTF-8.vcxproj]
> C:\ws\moveit2_ws\build\srdfdom\Release\test_cpp_nl_NL.UTF-8.exe : fatal error LNK1120: 1 unresolved externals [C:\ws\moveit2_ws\build\srdfdom\test_cpp_nl_NL.UTF-8.vcxproj]
> ```

Look like these errors should be fixed in https://github.com/ros-planning/srdfdom/pull/91, have you tried rebasing on it.?

**Comment by ooeygui** [comment]
@JafarAbdi Ack! I thought I cherry-picked your change into a fixed branch - checking now.

**Comment by ooeygui** [comment]
I can confirm that this change works for Windows and Linux! Thank you for fixing this @JafarAbdi

**Review by vatanaksoytezer — APPROVED** [review]
Looks good to me

**Review by henningkayser — APPROVED** [review]

**Pull request merged**
