### PR TITLE
Compile with -std=c++11

### PR DESCRIPTION
**Pull request by vmatare**

### CODE REVIEW

**Comment by de-vri-es** [comment]
Should be fine I think, but I wonder, did something break without the flag?

**Comment by vmatare** [comment]
`urdfdom_headers` switched from `boost::shared_ptr` to `std::shared_ptr` in [#729c4de](https://github.com/ros/urdfdom_headers/commit/729c4ded35d8bda7138d23d9c8503a9e0734ef63#diff-0bd69ccfb08deda22419438142b9a2c3), so if we compile against it, we need C++11.

**Review by de-vri-es — APPROVED** [review]
Right, makes sense. Looks good to me.

**Review by v4hn — APPROVED** [review]

**Comment by v4hn** [comment]
Thanks @vmatare !

**Pull request merged**
