### PR TITLE
Install headers into include/srdfdom/srdfdom

### PR DESCRIPTION
**Pull request by rhaschke**
... to make overlays work as suggested in https://github.com/moveit/moveit2/pull/3003#issuecomment-2405991554

### CODE REVIEW

**Comment by rhaschke** [comment]
Format failure is due to https://github.com/pre-commit/action/issues/213

**Review by sjahr — APPROVED** [review]
Thanks!

**Review by sea-bass — APPROVED** [review]

**Comment by sea-bass** [comment]
How do ROS releases work in terms of amending the 2.0.5 release that is queued for sync? Does this change make it 2.0.6, or can we do a 2.0.5-2 type thing since the release is not yet available?

**Comment by rhaschke** [comment]
We need to release as 2.0.6. 
The version suffix `-2` is automatically added by the buildfarm for a new build of the same release.

**Comment by rhaschke** [comment]
I will merge this and handle a new release as soon as https://github.com/rhaschke/moveit2/actions/runs/11315638584/job/31467055018 succeeds.

**Comment by rhaschke** [comment]
Release triggered: https://github.com/ros/rosdistro/pull/43168

**Pull request merged**
