### PR TITLE
[maint] add soname to library

### PR DESCRIPTION
**Pull request by tylerjw**
soname added to library for Noetic releases

### CODE REVIEW

**Review by v4hn — APPROVED** [review]
LGTM

**Comment by rhaschke** [comment]
@davetcoleman, we should discuss (and agree on a common strategy) whether or not to keep tags like `[maint]` in the commit message when merging. So far, we didn't.

**Comment by v4hn** [comment]
> we should discuss (and agree on a common strategy) whether or not to keep tags like `[maint]` in the commit message when merging. So far, we didn't.

In theory these tags can be annotated as github tags just as well (and would not appear in the commit), but few people use these tags at the moment.
Personally, I don't care whether some (or most) commits include a tag in the description, as long as the main content still fits the summary line.

**Comment by davetcoleman** [comment]
Yea I don't think we need to over-dictate how people write their commit messages. Though I do like the "WIP" standard as we have a bot that enforces PRs from not being merged until its removed.

**Comment by rhaschke** [comment]
My key point was that I am fine with tags in github PR titles, but I would like to remove those tags when actually merging.

**Comment by tylerjw** [comment]
I put this tag in because I just did the cleanup for changelists.  It would be nice if these tags were in the commit message than the changelist generator would get them and it'd remove a manual step when generating a changelist (not that it is that bad).

**Comment by rhaschke** [comment]
IMO the tags clutter the git commit history. I see your motivation of avoiding the manual work for changelogs. But there, we need to format and cleanup manually anyway.

**Pull request merged**
