### PR TITLE
changelogs for noetic 0.6.0

### PR DESCRIPTION
**Pull request by tylerjw**

### CODE REVIEW

**Comment by tylerjw** [comment]
This is failing travis due to clang-format.  Should I make a clang-format fix PR before this to bring this up to clang-format-10 in line with what we did in moveit?  @rhaschke @v4hn

**Comment by tylerjw** [comment]
Here is that change: https://github.com/ros-planning/srdfdom/pull/66

I'll rebase this after we finish that one.

**Comment by rhaschke** [comment]
I didn't yet released srdfdom, because I think we should decide on https://github.com/ros-planning/srdfdom/pull/60 first.

**Comment by davetcoleman** [comment]
@rhaschke could you rebase quickly #60 so we can release this?

p.s. @tylerjw and I are on MoveIt Discord if you wanna join that for quicker chatting

**Comment by rhaschke** [comment]
> @rhaschke could you rebase quickly #60 so we can release this?

Will do.

**Comment by rhaschke** [comment]
@tylerjw, I will finish releasing this repo into Noetic.

**Pull request closed without merging**
