### PR TITLE
Use MoveIt! clang format for SRDF

### PR DESCRIPTION
**Pull request by davetcoleman**
@kkufieta

### CODE REVIEW

**Comment by jonbinney** [comment]
Looks good - I'm building this just to sanity check.

**Review by jonbinney — APPROVED** [review]
LGTM!

**Comment by rhaschke** [comment]
@jonbinney Please be more careful before merging. This PR was failing on Travis!

**Comment by jonbinney** [comment]
@rhaschke my mistake - will be more careful in the future.

To clarify, this didn't fail any of the existing checks. It added a new check that fails right now on melodic, since clang-format-3.8 package doesn't exist on 18.04. That should be fixed once https://github.com/ros-planning/moveit_ci/pull/39 is debugged and merged.

**Pull request merged**
