### PR TITLE
[Fix] missed naming problems

### PR DESCRIPTION
**Pull request by jeasinema**

### CODE REVIEW

**Comment by v4hn** [comment]
@IanTheEngineer broke this two weeks ago.
Merging.

@rhaschke I guess we need another release :sunglasses:

**Comment by rhaschke** [comment]
We definitely need a Melodic docker image for Travis tests! @davetcoleman, could you prepare this?

**Comment by IanTheEngineer** [comment]
@v4hn, let's not get too hasty on the blame there... I believe you're referring to PR https://github.com/ros-planning/srdfdom/pull/37 which lacks my fingerprints ;)

**Comment by v4hn** [comment]
@IanTheEngineer no I was referring to https://github.com/ros-planning/srdfdom/commit/7deee8cf50c560d1d09346b53f9e5f390cc4e827#diff-236dfd41d36580e127f9bdb8158d5419R348 which is clearly your commit :-)

No worries, you just supported my point that `CONSOLE_BRIDGE_logError` is a ridiculous function name in C++. :sunglasses:

**Comment by IanTheEngineer** [comment]
Ah, yes. That's a function of merge order - #36 was created prior to #37 (which changed logging) and not rebased prior to merging. Fair enough! Guilty as charged.

**Pull request merged**
